version = 0.1

extensions = ['chomp@0.1:jspm']

# Generate an import map for a browser HTML page
[[task]]
name = 'build:success:html'
target = 'public/success.html'
dep = 'src/success.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'production', 'module']
preload = true
integrity = true

[[task]]
name = 'build:error:html'
target = 'public/error.html'
dep = 'src/error.html'
template = 'jspm'
[task.template-options]
env = ['browser', 'production', 'module']
preload = true
integrity = true