name: CI/CD Error test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build using chomp
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Chomp
        uses: guybedford/chomp-action@v1
      - run: chomp build:error:html